# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy-dev:
    steps:
      - run: npm run deploy:dev

  deploy-prod:
    steps:
      - run: npm run deploy:prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: /feat\/.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
