# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # # run tests!
      # - run: npm test

      # run deploy!
  deploy-dev:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/app

    steps:
      - run: npm run deploy:dev

  deploy-prod:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/app

    steps:
      - run: npm run deploy:prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: /feat-.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
