# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
aliases:
  - &filter-prod-branch
    branches:
      only:
        - master

  - &filter-feat-branches
    branches:
      only:
        - /feat\/.*/

  - &root-restore-npm-cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - v1-dependencies-

  - &save-cache
    paths:
        - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - &npm-install |
    npm install

version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.10
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *root-restore-npm-cache
      - run: npm install
      - save_cache: *save-cache

  deploy-dev:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *root-restore-npm-cache
      - run: npm install
      - save_cache: *save-cache
      - run: npm run deploy:dev

  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *root-restore-npm-cache
      - run: npm install
      - save_cache: *save-cache
      - run: npm run deploy:prod

workflows:
  version: 2
  build-deploy-dev:
    jobs:
      - build:
          filters: *filter-feat-branches
      - deploy-dev:
          requires:
            - build

  build-deploy-prod:
    jobs:
      - build:
        filters: *filter-prod-branch
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - build
      - deploy-prod:
          requires:
            - hold
          filters: *filter-prod-branch
